default-enabled: true

defaults:
  drowning: false
  targeting: false
  hunger: false
  regeneration: false
  fall: false
  lava: false
  fire: false
  durability: false
  fireworks: false
  keep-inventory: false
  drop-vacuum: false
  trash: false
  backpack: false
  backpack-pickup: false

  experience-multiplier: 1.0
  block-break-speed: 1.0

players: {}
